### ISSUE TITLE
Couple of questions on usage.

### ISSUE THREAD

**Issue by ghost** [tampe125/hashtag-scraper#1]
-l  --lang , You mention en is default although if i want another lang do we use the standard 2 letter abbreviations, ie: de and fr. 

On the first pass I scraped 17k hashtags although it took sometime (4h30m), now if I where to re-run would the scraper likely find duplicates?

Great work and nice idea btw.

**Comment by tampe125** [comment]
Yes, if you want another language simply use a different code: `de`, `fr`, `it` etc etc, you get the idea.
Please keep in mind that sometimes the language code and the actual language tweet don't match. I suspect Twitter is simply filling the `lang` attribute depending on the site/location.  
This means that if I'm France and I write a tweet in English, it will be reported as a French tweet.

If you rerun it, yes you will found duplicates.
Actually, the script holds only a 500 list of hashtags, then it dumps them on a file, clearing the list. While filling the list, it avoids to save duplicates, however after the dump you could easily find more duplicates.
This is a tradeoff between result and performance: if we would check that every hashtag is really unique, the execution would take too much time and we wouldn't keep up with Twitter pace sending us data, so we would be disconnected.

To avoid duplicates, after scraping them, you can easily sort and unique the whole list using `sort -u`; if you are under Windows take a look at Cygwin.

**Comment by ghost** [comment]
Got it thanks, but I have another problem.

I can only surmise thats twitter is blocking me from doing anymore scraping.

i re-ran hashtag scraper with -e 8 this time and it just hangs with no output, it only took 9 mins to gather the first 500 tags in the first instance but it has now been over an hour with nothing to show.
